### Site info:
title: ALLEN 軟體開發誌
tagline: 軟體開發。讀書心得
author: Allen Chien
email: allenchien.tw@gmail.com
description: "Allen" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Allen, Python, EdgeX, Flasgger, Pandas"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://allenchien-tw.github.io" # the base hostname & protocol for your site
locale: en_US
permalink: /blog/:year/:month/:day/:title

### Personal info and site tools info:
#twitter_username: yulijia
#disqus_shortname: allenchien-tw
fb_username: tw.allenchien
github_username: allenchien-tw
favicon: "/images/favicon.ico"
aboutme: 我是 ALLEN 目前從事物聯網軟體開發的工作 # these are shown on aboutme-sidebar.
aboutme_photo: "/images/me.png"
google_analytics_key:   # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr),  Russian (ru), Turkish (tr), and Indonesian (id).

locales:
    en:
      Aboutme: "Hi, "
      Archives: "文章"
      Blogroll: "Blogroll"
      Categories: "分類"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "最新"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "首頁"
      About: "關於"
      #Guestbook: "Guestbook"
      #Subscribe: "Subscribe"

### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Freshman
        href: https://allenchien-tw.github.io
        title: Another Jekyll blog theme
      - name: author's website
        href: https://allenchien-tw.github.io
        title: Lijia Yu's website


### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
plugins: 
    - jekyll-sitemap
    - jekyll-paginate
paginate: 10
excerpt_separator: <!-- more -->
